DROP TABLE IF EXISTS public.CONTENER;
DROP TABLE IF EXISTS public.PEDIDO;
DROP TABLE IF EXISTS public.REALIZAR;
DROP TABLE IF EXISTS public.MESA;
DROP TABLE IF EXISTS public.CLIENTE;
DROP TABLE IF EXISTS public.CHEF;
DROP TABLE IF EXISTS public.PLATO;