-- Procedure que calcula el total de gasto de un cliente
CREATE OR REPLACE FUNCTION calcular_total_gastos_por_cliente()
    RETURNS TABLE (NOMBRE_CLIENTE VARCHAR, TOTAL_GASTOS NUMERIC) AS $$
BEGIN
    RETURN QUERY
    SELECT C.NOMBRE_CLIENTE, SUM(P.PRECIO_TOTAL) AS TOTAL_GASTOS
    FROM CLIENTE C
             JOIN PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE
    GROUP BY C.NOMBRE_CLIENTE;
END;
$$ LANGUAGE plpgsql;

-- Procedure que muestra los detalles de los pedidos en un rango de fechas
CREATE OR REPLACE FUNCTION MOSTRAR_DETALLES_PEDIDOS_POR_FECHA(FECHA_INICIO DATE, FECHA_FIN DATE)
    RETURNS TABLE (ID_PEDIDO INT, FECHA_PEDIDO DATE, PRECIO_TOTAL NUMERIC, NOMBRE_CLIENTE VARCHAR, NUMERO_MESA INT) AS $$
BEGIN
    RETURN QUERY
        SELECT P.ID_PEDIDO, P.FECHA_PEDIDO, P.PRECIO_TOTAL, C.NOMBRE_CLIENTE, M.NUMERO_MESA
        FROM PEDIDO P
                 JOIN CLIENTE C ON P.ID_CLIENTE = C.ID_CLIENTE
                 JOIN MESA M ON P.ID_MESA = M.ID_MESA
        WHERE P.FECHA_PEDIDO BETWEEN FECHA_INICIO AND FECHA_FIN
        ORDER BY P.FECHA_PEDIDO;
END;
$$ LANGUAGE plpgsql;